sudo: false
language: python
python:
  - "2.7"

notifications:
  email: false

before_install:
  - git clone https://github.com/csferrie/python-qinfer.git


install:
  - export PATH=./src/qinfer:$PATH
  - pip install -r requirements.txt

  # Install Qinfer from GitHub source
  - cd ./python-qinfer
  - python setup.py install
  - cd ..

script:
  - nosetests --with-coverage

after_success:
  - coveralls